from enum import Enum, auto
class InputMode(Enum):
    CURSOR = auto()
    KEYBOARD = auto()
class GazeDirection(Enum):
    LEFT = auto()
    RIGHT = auto()
    UP = auto()
    DOWN = auto()
    CENTER = auto()

class BlinkType(Enum):
    NONE = auto()
    SINGLE = auto()
    DOUBLE = auto()
    LONG = auto()

class Action(Enum):
    MOVE_LEFT = auto()
    MOVE_RIGHT = auto()
    MOVE_UP = auto()
    MOVE_DOWN = auto()
    SELECT = auto()
    OPEN_KEYBOARD = auto()
    CLOSE_KEYBOARD=auto()
    OPEN_TYPING_KEYBOARD =auto()
    CLOSE_TYPING_KEYBOARD=auto()
    KEYBOARD_ROTATE = auto()
    KEYBOARD_SELECT = auto()
    SWITCH_TAB = auto()
    HELP_ALERT = auto()
    BACK = auto()
    NONE = auto()
    OPEN_NOTES = auto()
    VOICE_INPUT = auto()
    VOICE_TOGGLE = auto()
    INSERT_CHAR = auto()
    SPACE = auto()
    BACKSPACE = auto()
    DONE = auto()
    GROUP_SELECT = auto()
    NUMBER_MODE = auto()
    LETTER_MODE = auto()
    BACK_MODE = auto()